### ISSUE TITLE
First Run - No DB

### ISSUE THREAD

**Issue by MarkFontenot** [ashleytdavis/streamflix-database#1]
## Issue:  
When running the `data_generation.py` script for the first time, there is no `Streamflix` database on the MySQL server.  So the script encounters a runtime exception. Stack Trace below. 

## To reproduce:
- Completely remove the database `Streamflix` from your MySQL instance (something like `DROP DATABASE Streamflix`) - don't do this via the script.  
- Run the `data_generation.py` script

## Likely Cause
- the `with_db_connection` decorator includes db name of `Streamflix` as part of the connection object creation. 

## Stack Trace

```
Traceback (most recent call last):
  File "/Users/mark/anaconda3/lib/python3.11/site-packages/mysql/connector/connection_cext.py", line 334, in _open_connection
    self._cmysql.connect(**cnx_kwargs)
_mysql_connector.MySQLInterfaceError: Unknown database 'Streamflix'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/mark/code/course_material/24f-cs3200/streamflix-database/StreamflixDatabase/data_generation.py", line 494, in <module>
    main()
  File "/Users/mark/code/course_material/24f-cs3200/streamflix-database/StreamflixDatabase/data_generation.py", line 480, in main
    initialize_database()
  File "/Users/mark/code/course_material/24f-cs3200/streamflix-database/StreamflixDatabase/data_generation.py", line 24, in wrapper
    conn = mysql.connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mark/anaconda3/lib/python3.11/site-packages/mysql/connector/pooling.py", line 322, in connect
    return CMySQLConnection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mark/anaconda3/lib/python3.11/site-packages/mysql/connector/connection_cext.py", line 151, in __init__
    self.connect(**kwargs)
  File "/Users/mark/anaconda3/lib/python3.11/site-packages/mysql/connector/abstracts.py", line 1399, in connect
    self._open_connection()
  File "/Users/mark/anaconda3/lib/python3.11/site-packages/mysql/connector/connection_cext.py", line 339, in _open_connection
    raise get_mysql_exception(
mysql.connector.errors.ProgrammingError: 1049 (42000): Unknown database 'Streamflix'
```

**Comment by ashleytdavis** [comment]
Should be fixed - passed on database creation to data_generation script. Script now checks if database already exists, if not, creates database
